### ISSUE TITLE
Tree.rootNode undefined in jest tests due to race condition

### ISSUE THREAD

**Issue by sdtblck** [tree-sitter/node-tree-sitter#181]
Hi! Thanks so much for tree-sitter, such a great tool.

I'm running into what I think is [this bug](https://github.com/tree-sitter/node-tree-sitter/pull/75) during jest testing. tl;dr: I'm trying to access `tree.rootNode`, and it's unexpectedly undefined. This only happens when I run multiple tests at once - if I run just the failing test individually, it no longer fails.

I noticed there was a 'fix' merged in https://github.com/tree-sitter/node-tree-sitter/pull/164/files#diff-2684fb8518715da16bb9878add03aa5ab02197200677f48d4dd60b7be904b6c0 - but this doesn't seem like an actual fix? rather, it fixes the tests in node-tree-sitter, but not the underlying issue for any end users.

[This PR](https://github.com/tree-sitter/node-tree-sitter/pull/75) seems to address the actual issue, and prevent the rootNode variable from being overwritten when the context is reloaded. Is there any chance of getting this merged? I'd be happy to contribute to bringing it up to date if so.

**Comment by segevfiner** [comment]
This might have been fixed by https://github.com/tree-sitter/node-tree-sitter/commit/7ff112ea98ad25796118bfbaa456523a10786967, we could possibly also restore the Jest based tests that existed before.

**Comment by jpulec** [comment]
Best I can tell, this appears to still exist on `v0.21.1`. Interestingly, I'm actually only able to reproduce it by running my jest tests without parallelization. Otherwise, using multiprocessing, my tests run fine.

**Comment by maksimr** [comment]
We had the same problem in our project. 
The root cause is Jest module loading system (https://github.com/jestjs/jest/issues/4413). Jest's rewrite nodejs' require on own implementation and re-evaluate module for new test file in the same process. 
This break `tree-sitter` because tree-sitter [relay on this behaviour and save some native functions from Parser.prototye in the module scope](https://github.com/tree-sitter/node-tree-sitter/blob/master/index.js#L333). So when Jest re-evaluate `tree-sitter/index.js` Parser.prototype will reference rewriten JavaScript implementation and `const {parse, setLanguage}` will reference on JavaScript not original functions from bindings.

As a workaround you can override path for `tree-sitter` on custom tree-sitter loader file, for example `tree-sitter-jest.js`
```js
  moduleNameMapper: {
    '^tree-sitter$': '<rootDir>/test/tree-sitter-jest.js',
  },
```

and in `tree-sitter-jest.js` use internal nodejs api to load `tree-sitter` which allows load module only once.

`tree-sitter-jest.js`
```js
// Jest's module reloading on each tests breaks the tree-sitter module
// So use native require to load `tree-sitter` module only for jest tests
// to prevent module reloading
// @see https://github.com/tree-sitter/node-tree-sitter/issues/181
const Module = require('node:module');
const internalNodeModuleLoader = Module._load;
const originalTreeSitterModulePath = require.resolve(
  // use `tree-sitter/index.js` for resolve instead of `tree-sitter`
  // because we override path for `tree-sitter` in moduleNameMapper
  'tree-sitter/index.js'
);
module.exports = internalNodeModuleLoader(originalTreeSitterModulePath);
```

The second, **better solution**, just get rid of hacky `jest` and use normal test runner for node. For example `jasmin`, `mocha` or native nodejs test runenr.

🍻

**Comment by peter-slattery** [comment]
Chiming in that:
a) this is indeed still an issue using tree-sitter 0.21.1 and jest 29.7.0
b) that @maksimr's suggestion of manually overriding tree sitter's path in jest works.
